# Generated by Django 2.1.3 on 2018-12-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leanRestApis', '0002_auto_20181207_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectactivity',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='projectactivity',
            old_name='parent_project_activity_id',
            new_name='parent_project_activity',
        ),
    ]
