# Generated by Django 2.1.3 on 2018-12-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leanRestApis', '0003_auto_20181207_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='parent_project_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leanRestApis.ProjectActivity'),
        ),
    ]
