# Generated by Django 2.1.3 on 2018-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanRestApis', '0004_auto_20181209_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='wbs_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
